[world]
name = "engine"
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://github.com/dojoengine/dojo-starter"
seed = "engine"

[world.socials]
github = "https://github.com/SoarinSkySagar/stark-tic-tac-toe"
telegram = "https://t.me/starktictactoe"

[namespace]
default = "engine"

[env]
rpc_url = "http://localhost:5050/"
# Default account for katana with seed = 0
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"
world_address = "0x050d7fc5593c05018872173d900886b503ff2510fb8ac5962b2513429b2431c2"

[writers]
"engine" = ["engine-actions"]
