name: Dojo Contracts CI
on:
   push:
       branches: ["main"]
   pull_request:
       branches: ["main"]
jobs:
   build-and-test:
       runs-on: ubuntu-latest
       steps:
           - name: Install Rust
             uses: actions-rs/toolchain@v1
             with:
                 toolchain: stable
                 override: true
                 
           - name: Install asdf
             uses: asdf-vm/actions/setup@v3
           
           - name: Checkout code
             uses: actions/checkout@v3

           - name: Install plugins
             run: |
                asdf plugin add scarb
                asdf install scarb latest
                asdf global scarb latest
                asdf plugin add dojo https://github.com/dojoengine/asdf-dojo
                asdf install dojo latest 
                asdf global dojo latest
           
           - name: Build contracts
             run: |
                 sozo build
           
           - name: Run tests
             run: |
                 sozo test
           
           - name: Check formatting
             run: scarb fmt --check
