name: Update Contributors
on:
  pull_request:
    types: [closed]
jobs:
  update-contributors:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Update README with Contributors
        env:
          CONTRIBUTOR_NAME: ${{ github.event.pull_request.user.login }}
          CONTRIBUTOR_AVATAR: ${{ github.event.pull_request.user.avatar_url }}
          CONTRIBUTOR_PROFILE: ${{ github.event.pull_request.user.html_url }}
        run: |
          # Check if Contributors section exists, if not add it
          if ! grep -q "## Contributors" README.md; then
            echo -e "\n## Contributors\n" >> README.md
          fi
          
          # Check if contributor already exists
          if ! grep -q "$CONTRIBUTOR_PROFILE" README.md; then
            # Use sed to insert before the last line
            sed -i '$d' README.md
            echo -e "<a href=\"$CONTRIBUTOR_PROFILE\"><img src=\"$CONTRIBUTOR_AVATAR\" width=\"50px\" alt=\"$CONTRIBUTOR_NAME\"/></a> " >> README.md
            echo "" >> README.md
          fi
          
      - name: Commit and push if changed
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "docs: update contributors" && git push)
